In [63]:
from sklearn.neural_network import MLPClassifier
from pandas import DataFrame as df
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import datasets
import numpy

In [35]:
#Loading the data
dataset = datasets.load_iris()

In [36]:
for keys in dataset.keys() :
    print(keys)

data
target
frame
target_names
DESCR
feature_names
filename
data_module


In [ ]:
X=dataset.data
print('data',X)
Y=dataset.target
print('target',Y)
print('target_names',dataset.target_names)

In [38]:
#Classify for the whole dataset
mlp=MLPClassifier(hidden_layer_sizes=(100,), activation='relu', solver='adam', alpha=0.0001, max_iter=800)
mlp.fit(X,Y)
pred=mlp.predict(X)
score=mlp.score(X,Y)

In [58]:
score

0.98

In [56]:
cm=confusion_matrix(Y,pred)
print(cm)

[[50  0  0]
 [ 0 48  2]
 [ 0  1 49]]


In [57]:
#Spliting data
x_train, x_val, y_train, y_val=train_test_split(X,Y, test_size=0.3, random_state=0)
#Training set
mlp=MLPClassifier(hidden_layer_sizes=(100,), activation='relu', solver='adam', alpha=0.0001, max_iter=800)
mlp.fit(x_train,y_train) #returns a trained mlp model in form of object named 'mlp'
predictions_train=mlp.predict(x_train)
accuracy_train=mlp.score(x_train, y_train)
print("Training set accuracy : ",accuracy_train)
#Validation set
predictions_val=mlp.predict(x_val)
accuracy_val=mlp.score(x_val, y_val)
print ("Validation set accuracy : ",accuracy_val)

Training set accuracy :  0.9809523809523809
Validation set accuracy :  0.9777777777777777


In [64]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(mlp, X, Y, cv=10)
scores
print(numpy.mean(scores))

0.9733333333333334
